
  
name: SSH Raspberry Deployment
on :
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - name: Connect
        run: |
          #sudo apt-get install sshpass
          #sudo ssh -tt -o StrictHostKeyChecking=No -p 69 pi@${{ secrets.VPS_HOST }}
          
          echo 
          echo ${bold}current path contents $normal
          echo
          sshpass -p ${{ secrets.USER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.USER }}@${{ secrets.VPS_HOST }} "ls -a"
          echo current path
          sshpass -p ${{ secrets.USER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.USER }}@${{ secrets.VPS_HOST }} "pwd"
          
          echo 
          echo ${bold}change folder and git checkout $normal
          echo
          sshpass -p ${{ secrets.USER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.USER }}@${{ secrets.VPS_HOST }} \
          "cd /home/pi/WDIC_Raspberry_RS485 \
          && sudo git checkout . \
          "
          echo 
          echo ${bold}change folder and git pull $normal
          echo
          sshpass -p ${{ secrets.USER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.USER }}@${{ secrets.VPS_HOST }} \
          "cd /home/pi/WDIC_Raspberry_RS485 \
          && git fetch --all \
          && git reset --hard origin \
          "
          echo 
          echo ${bold}Run Serial.py $normal
          echo
          sshpass -p ${{ secrets.USER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.USER }}@${{ secrets.VPS_HOST }} \
          "cd /home/pi/WDIC_Raspberry_RS485 \
          && python3 -m pytest -v -s\
          "
      
        # && sudo git pull git@github.com:Mrxpxpb/Advanced_Parking_Monitoring_Raspberry_Master.git